version: "3.8"

services:
  backend:
    image: ${DOCKER_USERNAME:-ecommerce}/ecommerce-backend:${BUILD_TAG:-latest}
    container_name: ecommerce-backend-prod
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=${CORS_ORIGIN}
      - MONGO_URL=${MONGO_URL_PROD}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health"]
      interval: 15s
      timeout: 3s
      retries: 5
    expose:
      - "5000"
    networks:
      - prod-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  frontend:
    image: ${DOCKER_USERNAME:-ecommerce}/ecommerce-frontend:${BUILD_TAG:-latest}
    container_name: ecommerce-frontend-prod
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 5
    expose:
      - "80"
    networks:
      - prod-network
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - prod-network
    restart: always
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy

networks:
  prod-network:
    driver: bridge
