version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME:-ecommerce}/ecommerce-backend:latest
    container_name: ecommerce-backend
    environment:
      - NODE_ENV=production
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME:-ecommerce}/ecommerce-frontend:latest
    container_name: ecommerce-frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
